name: CI
on:
  push:
    branches: ["**"]
  pull_request:
jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 22
      - name: Cache node_modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: node-deps-${{ hashFiles('package-lock.json') }}
          restore-keys: node-deps-
      - name: Install NPM dependencies
        run: npm ci
      - name: Audit NPM dependencies
        run: npm audit --audit-level=high
      - name: Run Tests (Vitest)
        run: npm run test -- --coverage
      - name: Build Library (Vite)
        run: npm run build
      - name: Upload Coverage Report
        if: ${{ success() && hashFiles('coverage/**') != '' }}
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: coverage/
